name: Build and test ShannonLoader

on:
  push:
    branches: [ master ]
    paths:
      - 'reversing/ghidra/ShannonLoader/**'
      - '!reversing/ghidra/ShannonLoader/*.md'
  pull_request:
    branches: [ master ]
    paths:
      - 'reversing/ghidra/ShannonLoader/**'
      - '!reversing/ghidra/ShannonLoader/*.md'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: reversing/ghidra/ShannonLoader

    env:
      GHIDRA_VERSION: ghidra_10.2.2_PUBLIC
      GHIDRA_BUILDDATE: 20221115

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: grant-h/ShannonFirmware
        path: reversing/ghidra/ShannonLoader/ShannonFirmware
    - name: Installing JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Download Ghidra ${{ env.GHIDRA_VERSION }}
      run: wget -q https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.2.2_build/${GHIDRA_VERSION}_${GHIDRA_BUILDDATE}.zip
    - name: Unzip Ghidra
      run: unzip -q ${GHIDRA_VERSION}_${GHIDRA_BUILDDATE}.zip
    - name: Build and pack extension
      run: GHIDRA_INSTALL_DIR=$(pwd)/${GHIDRA_VERSION} ./gradlew
    - name: Install extension to Ghidra
      run: unzip ./dist/ShannonLoader-*.zip -d ./${GHIDRA_VERSION}/Ghidra/Extensions
    - name: Test loader on firmware corpus
      run: GHIDRA_INSTALL_DIR=$(pwd)/${GHIDRA_VERSION} ./scripts/ShannonFirmwareProcess.py $(pwd) ShannonProject ./ShannonFirmware/modem_files
